version: "3.8"

services:
    redis:
        image: redis
        restart: "always"
        ports:
            - "${REDIS_PORT:-6379}:6379"

    # PostgreSQL database and Adminer (db management tool)
    postgres:
        image: postgres
        ports:
            - "${POSTGRES_PORT:-5432}:5432"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 20

    adminer:
        image: adminer
        ports:
            - "${ADMINER_PORT:-8080}:8080"
        depends_on:
            postgres:
                condition: service_healthy
